# Generated by Django 5.2.3 on 2025-06-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nuevonivel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevoNivel',
        ),
    ]
