# Generated by Django 5.2.3 on 2025-06-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_nuevonivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevo_nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
