# Generated by Django 5.2.3 on 2025-06-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nuevo_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
