# Generated by Django 5.2.3 on 2025-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usuario_nombre_de_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
