# Generated by Django 5.2.3 on 2025-06-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_nombre_de_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nuevo_nivel',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
