# Generated by Django 5.2.3 on 2025-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_nuevo_nivel_alter_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveleducativo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
