# Generated by Django 5.2.3 on 2025-06-21 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_correo_personal_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.persona'),
        ),
    ]
